export const START_FETCHING_CATEGORIES = 'features/Categories/START_FETCHING_CATEGORIES';
export const ERROR_FETCHING_CATEGORIES = 'features/Categories/ERROR_FETCHING_CATEGORIES';
export const SUCCESS_FETCHING_CATEGORIES = 'features/Categories/SUCCESS_FETCHING_CATEGORIES';
